app:

  protocol: http
  domain: 39.105.101.248
  port: 86

  business:
    market:
      lock:
        expire: 5

eth:

  protocol: http
  domain: 54.255.204.122
  port: 80

  contract:
    exchange: '0xb2397c9171CE9AbC209248eEEf29252634Ce8Be5'
    smartup: '0x184a3dad8912a81ab393b83892f2039ec0297132'
    sut: '0xf1899c6eb6940021c1ae4e9c3a8e29ee93704b03'
    ntt: '0x846ce03199a759a183cccb35146124cd3f120548'

spring:

  profiles:
    active: test

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/smartup_node?useSSL=false
    username: root
    password: cherry2018
    sql-script-encoding: UTF-8

    druid:
      initial-size: 1
      max-active: 20
      min-idle: 5
      connection-init-sqls: set names utf8mb4

  redis:
    host: 127.0.0.1
    port: 6379
    password: cherry2018
    pool:
      max-active: 2
      min-idle: 1
      max-wait: 5000

mybatis:
  check-config-location: false
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mapper:
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
  style: camelhump

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

server:
  port: 8085
  max-http-header-size: 10240

logging:
  level:
    org.springframework: info
    global.smartup.node: info